// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// frame_keeper //
// ------------ //

#define frame_keeper_wrap_target 1
#define frame_keeper_wrap 7
#define frame_keeper_pio_version 0

static const uint16_t frame_keeper_program_instructions[] = {
    0x2092, //  0: wait   1 gpio, 18
            //     .wrap_target
    0x2012, //  1: wait   0 gpio, 18
    0xc042, //  2: irq    clear 2
    0xc000, //  3: irq    nowait 0
    0x2092, //  4: wait   1 gpio, 18
    0xc043, //  5: irq    clear 3
    0xc044, //  6: irq    clear 4
    0xc001, //  7: irq    nowait 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program frame_keeper_program = {
    .instructions = frame_keeper_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = frame_keeper_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config frame_keeper_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + frame_keeper_wrap_target, offset + frame_keeper_wrap);
    return c;
}
#endif

// ----------- //
// time_keeper //
// ----------- //

#define time_keeper_wrap_target 0
#define time_keeper_wrap 2
#define time_keeper_pio_version 0

static const uint16_t time_keeper_program_instructions[] = {
            //     .wrap_target
    0x2014, //  0: wait   0 gpio, 20
    0x2094, //  1: wait   1 gpio, 20
    0xc043, //  2: irq    clear 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program time_keeper_program = {
    .instructions = time_keeper_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = time_keeper_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config time_keeper_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + time_keeper_wrap_target, offset + time_keeper_wrap);
    return c;
}
#endif

// ------------ //
// interface_rx //
// ------------ //

#define interface_rx_wrap_target 2
#define interface_rx_wrap 4
#define interface_rx_pio_version 0

static const uint16_t interface_rx_program_instructions[] = {
    0xa0c3, //  0: mov    isr, null
    0xc022, //  1: irq    wait 2
            //     .wrap_target
    0xc023, //  2: irq    wait 3
    0x00c0, //  3: jmp    pin, 0
    0x4001, //  4: in     pins, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program interface_rx_program = {
    .instructions = interface_rx_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = interface_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config interface_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + interface_rx_wrap_target, offset + interface_rx_wrap);
    return c;
}
#endif

// ------------ //
// interface_tx //
// ------------ //

#define interface_tx_wrap_target 0
#define interface_tx_wrap 10
#define interface_tx_pio_version 0

static const uint16_t interface_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe346, //  1: set    y, 6                   [3]
    0x0782, //  2: jmp    y--, 2                 [7]
    0xfb42, //  3: set    y, 2            side 1 [3]
    0x0784, //  4: jmp    y--, 4                 [7]
    0xf047, //  5: set    y, 7            side 0
    0x2014, //  6: wait   0 gpio, 20
    0x6081, //  7: out    pindirs, 1
    0x2094, //  8: wait   1 gpio, 20
    0x0086, //  9: jmp    y--, 6
    0xe080, // 10: set    pindirs, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program interface_tx_program = {
    .instructions = interface_tx_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = interface_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config interface_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + interface_tx_wrap_target, offset + interface_tx_wrap);
    sm_config_set_sideset(&c, 2, true, true);
    return c;
}
#endif

